### ISSUE TITLE
特定のオプションを指定すると、結果が必ずShift_JISになってしまう。

### ISSUE THREAD

**Issue by neko-kusa** [kkato233/nkf#6]
特定のオプションを指定すると、結果が必ずShift_JISになってしまうようです。

例： 
UTF-8文字列に --katakana-hiraganaを指定した場合、
UTF-8が返らず、Shift_JISが返って来てしまう。

・判明しているオプション
--katakana-hiragana
--numchar-input
-Z0 
-Z1
-Z2
-Z3
-Z4
-xM
-xm
-W16B0xw
-W32B0xw

**Comment by kkato233** [comment]
出力のエンコード指定は `--oc=utf-8` や `-w` と組み合わて下さい。

コード例
```
nkf.exe --oc=utf-8 --katakana-hiragana < 入力ファイル > 出力ファイル
```
または
```
nkf.exe -w --katakana-hiragana < 入力ファイル > 出力ファイル
```

**Comment by neko-kusa** [comment]
ありがとうごいざいます。当方の理解不足でした、

**Comment by kkato233** [comment]
マニュアルが分かりにくいのが問題なので、そのうち 解説を増やしていきます。
